### PR TITLE
Value should return nil if the id is nil

### PR DESCRIPTION
**Pull request by olivoil**
So that it saves as null instead of "000000000000000000000000000" in sql

### CODE REVIEW

**Comment by achille-roussel** [comment]
Hello, thanks for submitting a pull request!

I have mixed feelings about this change:

- Intuitively it _makes sense_, especially because the zero value is called `ksuid.Nil` in the package, but also because it's documented as being an invalid value for a KSUID.

- Practically it means that a table column that was typed `char(27) not null` will now fail to insert zero-values of KSUIDs. Maybe this is what we want as it sounds like a bug, but at the same time it could be a breaking change for programs depending on this package.

@rbranson what are your thoughts on that?

**Comment by olivoil** [comment]
@achille-roussel @rbranson my main concerns are that:

- a column declared as `CHAR(27)` saves nil values as `'000000000000000000000000000'`, and will sometimes provoke errors if used with a foreign key constraint
- a column declared as `CHAR(27) NOT NULL` will not throw errors when saving with `ksuid.Nil`, when I would actually expect an error

An alternate solution to avoid breaking changes could also be to implement a NullType, which I’ve been doing in the meantime. Something like:

```go
type NullID struct {
	KSUID ksuid.KSUID
	Valid bool
}

// Scan implements the Scanner interface.
func (ks *NullID) Scan(value interface{}) error {
	if value == nil {
		ks.KSUID, ks.Valid = ksuid.Nil, false
		return nil
	}

	err := ks.KSUID.Scan(value)
	if err != nil {
		ks.Valid = false
		return err
	}

	ks.Valid = true
	return nil
}

// Value implements the driver Valuer interface.
func (ks NullID) Value() (driver.Value, error) {
	if !ks.Valid {
		return nil, nil
	}
	return ks.KSUID.String(), nil
}
```

**Comment by achille-roussel** [comment]
I agree with you that the change you suggest here would make the code more intuitive. I doubt there's code out there relying on having nil KSUIDs be stored as zeros, but it's impossible to tell.

I think our options are:
- not modify the current behavior and introduce the null type that you suggest
- modify the default behavior but offer a way to fallback to the current behavior with minimal code changes (assuming foreign packages have vendored ksuid, and they'll stay on top of the changelog if they want to upgrade)

**Comment by olivoil** [comment]
That makes sense. It does sound odd that someone would be relying on Nil saving as zeros, so I would vote for changing the default behavior and documenting the change.

**Comment by achille-roussel** [comment]
We discussed offline and we feel like the change makes sense, and the current behavior is broken more than anything.

Happy to merge, thanks for your contribution 👍

**Pull request merged**
