### PR TITLE
Added OrNil functions

### PR DESCRIPTION
**Pull request by V1def**

### CODE REVIEW

**Review by achille-roussel — COMMENTED** [review]
Thanks for the submission. 

Would you be able to provide context on what motivated this change?

**Comment by V1def** [comment]
Ease of use, there are cases where you are sure that your ksuid is correct. But you need to get from bytes or string, example below.

```go
func getPosts(before, after []byte) {
	b, err := ksuid.FromBytes(before)
	if err != nil {
		panic(err)
	}

	a, err := ksuid.FromBytes(after)
	if err != nil {
		panic(err)
	}

	sortOptions := SortOptions{Before: b, After:  a}
}
```

Instead, you can do it like this:

```go
func getPosts(before, after []byte) {
	sortOptions := SortOptions{
		Before: ksuid.FromBytesOrNil(before),
		After:  ksuid.FromBytesOrNil(after),
	}
}
```

KSUID already has something similar, `ksuid.New()`, only this function panics on error. OrNil functions are also used in many other packages (uuid, snowflake, ulid).

**Comment by achille-roussel** [comment]
Thanks for sharing context!

Do you mind adding a section to the README with these examples to showcase how to use the new functions? Along with links to the other libraries you mentioned would be amazing as well!

**Comment by V1def** [comment]
Yes, thank you.

**Review by achille-roussel — APPROVED** [review]
Thank you for the contribution!

**Pull request merged**
