### PR TITLE
doc: Adds a link to ksuid implementation in PHP.

### PR DESCRIPTION
**Pull request by gustavofreze**

### CODE REVIEW

**Comment by gustavofreze** [comment]
@achille-roussel Could you review my PR?

**Comment by achille-roussel** [comment]
Hello!

Thanks for the contribution. I am not at Segment anymore and therefore don't have the ability to merge the changes, but someone from their engineering team should be able to review and help get this merged in.

**Comment by gustavofreze** [comment]
@mericsson Could you review my PR?

**Comment by gustavofreze** [comment]
@mericsson Could you review my PR, please?

**Pull request closed without merging**
